=== Ceofy/ndexutils/tsv/loading_plan_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "NDEx TSV Loading Plan",
    "description": "Loading plan used by TSV loader",

    "definitions": {

      "NodeMapping": {
        "type": "object",
        "properties": {
          "id_prefix": {
            "description": "Prefix that need to be added to the id column",
            "type": "string"
          },
          "id_column": {
           "description": "Column that will be used as the represent field of a node. The first non-empty value in the list will be used to populate the node represent field.",
            "type": "string"
          },
          "node_name_column": {
            "description": "The name of a node. If id_column is missing in this object, the node_name will be used as a unique id of a node. This version of TSV loader requires node name to be unique in a network",
            "type": "string"
          },
          "property_columns": {
            "description": "Defines the mapping of all node properties. An Each of the non-empty value in these columns ",
            "type": "array",
            "items" : {
              "type" : "string"
            }
          }

        },
        "additionalProperties": false,
        "anyOf": [
            {
              "type":"object",
              "required": ["id_column"]
            },
            {
              "type":"object",
              "required": ["node_name_column"]
            }
          ]
      }

    },

    "type": "object",
    "properties": {
        "context": {
          "description": "Declare the namespaces that are used in this TSV file.",
          "type": "object",
           "patternProperties": {
                "^[^/@\\$\\^]+$": {
                  "type": "string",
                  "format": "uniref"
                }
            },
            "additionalProperties": false
        },
        "source_plan": {
            "description": "Mapping of the source nodes",
            "$ref": "#/definitions/NodeMapping"
        },
        "target_plan": {
             "description": "Mapping of the target nodes",
            "$ref": "#/definitions/NodeMapping"
        },
        "edge_plan": {
          "type": "object",
          "properties": {
            "default_predicate": {
              "description": "default value for edge name (interaction name).",
              "type": "string"
            },
            "predicate_id_column": {
              "description": "column that specify the edge name. If the value in this cell is missing, we will use the value defined in 'defalut_predicate', if it exists.",
              "type": "string"
            },
            "predicate_prefix": {
              "type": "string"
            },
            "citation_id_column": {
              "description": "Data in this column will be added as a edge property called 'citiation_ids'. Value in the cells of this column can be a single id or a comma seperated id list.",
              "type": "string"
            },
            "citation_id_prefix": {
              "description": "The prefix need to be added to the citation. If it is a list defining this prefix value will cause an error",
              "type": "string"
            },
            "property_columns": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false

        }

    },
    "additionalProperties": false,
    "required": ["source_plan","target_plan","edge_plan"]

}

=== Ceofy/ndexutils/ndexutil/tsv/test/ctd_disease_pathway-plan.json
{
    "context":
        {
            "mesh": "http://identifiers.org/mesh/",
            "omim": "http://identifiers.org/omim/"
        },

    "source_plan": 
    {
        "id_column": "Disease ID",
        "node_name_column": "DiseaseName"
    },
    "target_plan": 
    {
        "id_column": "PathwayName",
        "node_name_column": "PathwayName",
        "property_columns": ["Pathway Source"]
    },
    "edge_plan": 
    {
        "default_predicate": "affects",
        "property_columns": ["Pathway Source",
                            "Inference Gene Symbol"]
    }
}

=== Ceofy/ndexutils/ndexutil/tsv/test/bindingdb-plan.json
{
  "context": {
      "cid": "https://pubchem.ncbi.nlm.nih.gov/compound/",
      "uniprot": "http://identifiers.org/uniprot/",
      "pubmed": "http://identifiers.org/pubmed/"
  },

  "source_plan": {
    "id_prefix": "",
    "id_column": "PubChem CID",
    "node_name_column": "BindingDB Monomer ID",
    "property_columns": [
      "BindingDB Compound Page",
      "Compound SMILES",
      "US Patent Number",
      "Commercial Supplier"
    ]
  },
  "target_plan": {
    "id_prefix": "uniprot",
    "id_column": "Target UniProt ID",
    "node_name_column": "Target Name",
    "property_columns": [
      "BindingDB Target Page"
      
    ]
  },
  "edge_plan": {
    "default_predicate": "binds",
    "property_columns": [
      "Affinity Type",
      "Affinity (nM)",
      "BindingDB Details of Measurement",
      "All BindingDB Data for Ligand-Target Pair",
      "Data Curation Source"
    ],
    "citation_id_prefix": "pubmed",
    "citation_id_column": "PMID"
  }

}

=== Ceofy/ndexutils/ndexutil/tsv/test/Lit-BM-13-plan.json
{
    "context": {
            "NCBI Gene": "http://identifiers.org/ncbigene/"
    },

    "source_plan":
    {
        "id_prefix": "NCBI Gene",
        "id_column": "entrez_gene_ida",
        "node_name_column": "symbol_a",
        "property_columns": []
    },
    "target_plan": 
    {
        "id_prefix": "NCBI Gene",
        "id_column": "entrez_gene_idb",
        "node_name_column": "symbol_b",
        "property_columns": []
    },
    "edge_plan": 
    {
        "default_predicate": "interacts with",
        "property_columns": []
    }
  }

=== Ceofy/ndexutils/ndexutil/tsv/test/mgdb_mutations-plan.json
{
    "context": {
            "ncbigene": "http://identifiers.org/ncbigene/"
        },
    "source_plan": 
    {
        "id_prefix":"ncbigene",
        "id_column": "Gene ID",
        "node_name_column": "Gene Symbol",
        "property_columns": [""]
    },
    "target_plan": 
    {

        "id_column": "Genomic Locus",
        "node_name_column": "CDS Mutation",
        "property_columns": ["Genomic Locus"]
    },
    "edge_plan": 
    {
        "default_predicate": "has mutation",
        "property_columns": ["Primary Tissue",
                             "Histology",
                             "Genomic Locus"]
    }
}
